// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6BilvS0JAtoPT6QzTiUKarCru2VA3VE',
    appId: '1:515560094088:web:f39313cc74c717cb00a23d',
    messagingSenderId: '515560094088',
    projectId: 'savily-4e2b5',
    authDomain: 'savily-4e2b5.firebaseapp.com',
    storageBucket: 'savily-4e2b5.firebasestorage.app',
    measurementId: 'G-H0T31SB3SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7dv0kGtIjcTQhS3qN8xglgGjw90bePuo',
    appId: '1:515560094088:android:101b061400ff521700a23d',
    messagingSenderId: '515560094088',
    projectId: 'savily-4e2b5',
    storageBucket: 'savily-4e2b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ka7Y7mCr2hvxNta27a7nDgugbul10Cs',
    appId: '1:515560094088:ios:30a416b4ddca85db00a23d',
    messagingSenderId: '515560094088',
    projectId: 'savily-4e2b5',
    storageBucket: 'savily-4e2b5.firebasestorage.app',
    iosClientId: '515560094088-gsed2i89ok91p22n5bo1th60p10lfcb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveily2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ka7Y7mCr2hvxNta27a7nDgugbul10Cs',
    appId: '1:515560094088:ios:30a416b4ddca85db00a23d',
    messagingSenderId: '515560094088',
    projectId: 'savily-4e2b5',
    storageBucket: 'savily-4e2b5.firebasestorage.app',
    iosClientId: '515560094088-gsed2i89ok91p22n5bo1th60p10lfcb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveily2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa6BilvS0JAtoPT6QzTiUKarCru2VA3VE',
    appId: '1:515560094088:web:a1c493d6bc151d2f00a23d',
    messagingSenderId: '515560094088',
    projectId: 'savily-4e2b5',
    authDomain: 'savily-4e2b5.firebaseapp.com',
    storageBucket: 'savily-4e2b5.firebasestorage.app',
    measurementId: 'G-FN3C4LRLYG',
  );
}
